---
- name: Checking connection
  hosts: all
  gather_facts: false
  tasks:
    - ping:

- name: Group hosts
  hosts: all
  tasks:
    # - debug:
    #     msg: System {{ inventory_hostname }} using OS {{ ansible_distribution }} version {{ ansible_distribution_version }}
    - name: Group hosts by OS Family
      group_by:
        key: "os_{{ ansible_os_family }}";
      register: group_hosts

    - debug:
        var: group_hosts
