---
# docker edition
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

# apt config for Debian/Ubuntu
docker_apt_gpg_key: https://download.docker.com/linux/{{ansible_distribution | lower}}/gpg
docker_apt_ignore_key_error: true
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

# yum config for RedHat/CentOS
docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo
docker_yum_repo_enable_edge: '0'
docker_yum_repo_enable_test: '0'
docker_yum_repo_enable_nightly: '0'
docker_yum_gpg_key: https://download.docker.com/linux/centos/gpg

# Service options.
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# Docker Compose options.
docker_install_compose: true
docker_compose_version: "1.26.2"
docker_compose_variant: "{{ ansible_system }}-{{ ansible_architecture }}"
docker_compose_path: /usr/local/bin/docker-compose

# List of users to add to docker group
docker_users: ["vagrant"]
